### ISSUE TITLE
OTP 24.0 build is broken

### ISSUE THREAD

**Issue by brightball** [elixir-buildpack/heroku-otp#2]
Some folks over at Elixir Forum dug into it and appear to have found the issue. Just wanted to report it.

https://elixirforum.com/t/does-anybody-know-who-the-elixir-buildpack-team-is/39760

**Comment by al2o3cr** [comment]
Some history on how this situation appears to have happened:

* the canonical `config.sub` file has returned `x86_64-pc-linux-gnu`, since [this commit in 1996 changed it from `unknown` to `pc`](http://git.savannah.gnu.org/cgit/config.git/commit/?id=b7ab42761455e051a57876252740cb398aa952eb)
* BUT that change wasn't reflected in the canonical `config.guess` file until [people noticed in July 2015](https://lists.gnu.org/archive/html/config-patches/2015-06/msg00013.html)
* BUT the autoconf files in the OTP build were last copied from the canonical sources in... [March 2015](https://github.com/erlang/otp/commits/master/erts/autoconf/config.guess)

**Comment by KazW** [comment]
I'll try and get this fixed later tonight or on Saturday if it's more complicated than it seems, it looks like it should be fixed by setting the `RELEASE_ROOT` for the `make release` phase. Thanks for the research @al2o3cr!

**Comment by KazW** [comment]
This should be taken care of now. I deleted the releases and tags for 24.0, they should automatically be built during the next release sync, which should happen any minute now.

**Comment by KazW** [comment]
Looks like setting the environment variable didn't solve it completely, there's a strange error when make release is run. I'll try one more thing based the examples in the docs. I'll be asleep for the next release sync, so hopefully I wake up to some nice 24.0 binaries.

If the builds are still failing in the morning, I'll dig into the OTP makefiles. If I can't figure it out, I'll open an issue in the erlang/otp repo.
